version: '2'
services:
  evaskeleton_source:
      image: "evaengine/evaskeleton-source:${VERSION}"

  evaskeleton_node:
      build: ./dockerfiles/node
      image: "evaengine/evaskeleton-node:${VERSION}"
      restart: always
      expose:
         - 19000
      volumes_from:
        - evaskeleton_source
      environment:
        PORT: 19000

  evaskeleton_nginx:
      build: ./dockerfiles/nginx
      image: "evaengine/evaskeleton-nginx:${VERSION}"
      links:
        - evaskeleton_node
