version: '2'

services:

  evaskeleton_source:
      build: ./

  evaskeleton_node:
      environment:
        NODE_ENV: production

  evaskeleton_nginx:
      ports:
        - "80:80"
      environment:
        VIRTUAL_HOST: skeleton.evaengine.com
      extra_hosts:
        evaskeleton_swagger: 127.0.0.1
