version: '2'
services:

  evaskeleton_source:
      container_name: evaskeleton_source
      build: ./dockerfiles/source
      volumes:
        - .:/opt/htdocs/evaskeleton

  evaskeleton_node:
      container_name: evaskeleton_node
      command: "npm run dev"
      environment:
        NODE_ENV: "development"
        LOG_LEVEL: "debug"
        DB_REPLICATION_WRITE_HOST: "${MACHINE_IP}"
        DB_REPLICATION_READ0_HOST: "${MACHINE_IP}"
        DBREADONLY_HOST: "${MACHINE_IP}"

  evaskeleton_swagger:
      image: "evaengine/evaskeleton-node:${VERSION}"
      environment:
        LOG_LEVEL: "debug"
        NODE_ENV: "development"
        PORT: 15638
      expose:
         - 15638
      restart: always
      volumes_from:
        - evaskeleton_source
      container_name: evaskeleton_swagger
      command: "npm run swagger"
      environment:
        PORT: 15638
        SWAGGER_HOST: swagger.evaengine.com

  evaskeleton_nginx:
      container_name: evaskeleton_nginx
      networks:
        - default
        - nginx-proxy
      environment:
        VIRTUAL_HOST: local.evaengine.com,swagger.evaengine.com
        VIRTUAL_PORT: 80


networks:
  nginx-proxy:
    external:
      name: nginx-proxy