version: '2'

services:

  evaskeleton_source:
      build: ./

  evaskeleton_node:
      environment:
        NODE_ENV: test
        LOG_LEVEL: debug

  evaskeleton_nginx:
      networks:
        - default
        - nginx-proxy
      environment:
        VIRTUAL_HOST: test.evaengine.com
        VIRTUAL_PORT: 80


networks:
  nginx-proxy:
    external:
      name: nginx-proxy