eva_skeleton_source:
    build: ./source
    volumes:
      - ~/opt/htdocs/EvaSkeleton.js:/opt/htdocs/EvaSkeleton.js

eva_skeleton_nginx:
    build: ./nginx
    ports:
      - "80:80"
    links:
      - eva_skeleton_node
    volumes_from:
      - eva_skeleton_source

eva_skeleton_node:
    build: ./nodejs
    ports:
      - "19000:19000"
    links:
      - eva_skeleton_redis
      - eva_skeleton_mysql
    volumes_from:
      - eva_skeleton_source

eva_skeleton_mysql:
    build: ./mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456

eva_skeleton_redis:
    build: ./redis
    ports:
      - "6379:6379"
